# Generated by Django 3.2.5 on 2021-10-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
